[package]
name = "screenshot"
version = "0.1.0"
authors = ["robmikh <rob.mikh@outlook.com>"]
edition = "2018"

[dependencies]
winrt = { git = "https://github.com/microsoft/winrt-rs.git" }
clap = "2.33.3"
bindings = { path = "bindings" }

